version: "3.7"

services:
  nginx:
    environment:
      DOMAIN_URL: ${RELAY_URL}
      NODE_ENV: production
      EMAIL: ${CERTBOT_EMAIL}
      NODE_DOCKER_NAME: node
      NODE_PORT: 5000

  node:
    environment:
      NODE_ENV: production
